language: cpp

compiler: gcc
env:
  global:
    - COMPILER=g++-4.9
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "BCRrzi5am9lXXQ526c7X0CS0b4POiec/f+XztuEymSaFKHc6l0hGSWaCoeJ416VyFoRvVPG5MgUkrk9VUDG82QWoyVYwZUJu/fRfzjG0ENS7FOlR5Qev0/VGckQ00mFPXLF+UFAVUsJOHBVqD37rdJfZW2aG33oEgiS8J8seQB4m7mfQnqAGkSW0enLvf+3Knwy2Mjl4PG1JsgnSCN+RkRhu+XKL9wkpzIq+dRMMpfjzWuVImdfuVsYlPNQXestHOyl5mYdRFfoY0JNusxJCcCBHZytODipOAXzftq2sJ17TJmCcwSiogg1eQjVf/rchHsBFJwVkERWLNqtRhbuHDZO6TRUhf+w7fXn6yEVYopNBFY+uRxJ9Ilt+zqJGAS7QP/BgK4PQW/4wkRCgqQsylHdt4lvYRCeHboyv5wCreG3OhFaFsTH84PT8tCoOe8Jns94g/7hzKDnn2VbE7kIr7zKWJdkAywvVk80CNgccVFXVxnpEN2Z2ImsGvFo3fdWAhuc8uNM6aBR2DAO3GYyOm0vixrP3Wlz+YSXMkByspGPlTNcyA9GQ9HNuOuGmeqHUYuUwG/2lN+KA3ujz9/DYVmb4GVmRx50ilBQwXdfOOqFSR1+EiGjcq25umfp0we396+M+euaiLfvo2Lu56zYEy4gzOsxo6hGpdPql44GHKs8="

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-4.9','valgrind']
  coverity_scan:
    project:
      name: "FragJage/xPLHub"
      description: "This is a software hub for xPL protocol."
    notification_email: inscrip.jage@free.fr
    build_command_prepend: "cov-configure --comptype g++ --compiler $(which $COMPILER) && cmake . -G'Unix Makefiles' -DCMAKE_CXX_COMPILER=$(which $COMPILER)"
    build_command: "make"
    branch_pattern: coverity_branch
    
install:
  - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git

script:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then cmake . -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $COMPILER); fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then make; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ./test/bin/unittest; fi

after_success:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then valgrind --error-exitcode=1 --leak-check=full ./test/bin/unittest; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then coveralls --include src --gcov-options '\-lp' --gcov 'gcov-4.9'; fi
